version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --registry-ids $AWS_ACCOUNT_ID --region us-west-2)
      - git config --global url."git@github.com:".insteadOf "https://github.com/"
      - git init
      - git remote add origin git@github.com:ashishgupta023/neo-ai-dlr.git
      - git fetch
      - git checkout -t origin/master-docker-build-2
      - git submodule init
      - git submodule update --recursive
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --build-arg APP=xgboost -t $IMAGE_REPO_NAME:$IMAGE_TAG -f container/Dockerfile.cpu .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG